# Generated by Django 6.1.1 on 2026-09-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('airline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('airline_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('airline_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_iata', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_icao', models.CharField(blank=True, max_length=20, null=True)),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=150, null=True)),
                ('departure_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_gate', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_scheduled', models.DateTimeField(blank=True, null=True)),
                ('departure_actual', models.DateTimeField(blank=True, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=150, null=True)),
                ('arrival_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_gate', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_scheduled', models.DateTimeField(blank=True, null=True)),
                ('arrival_estimated', models.DateTimeField(blank=True, null=True)),
                ('arrival_actual', models.DateTimeField(blank=True, null=True)),
                ('aircraft_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('aircraft_iata', models.CharField(blank=True, max_length=20, null=True)),
                ('aircraft_icao', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('speed_horizontal', models.FloatField(blank=True, null=True)),
                ('speed_vertical', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('landed', 'Landed'), ('cancelled', 'Cancelled'), ('incident', 'Incident'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('data_source', models.CharField(default='aviationstack', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
